Revert "Allow python-docker versions greater than 0.5.0."
fix problem when starting dispatcher because docker-py 1.0 is not
compatible with docker version:

docker.errors.APIError: 404 Client Error: Not Found ("client and server
don't have same version (client : 1.17, server: 1.15)")

This reverts commit 3be8e2e23f48561d4962a320c8497484774b119a.